services:
  api:
    build:
      context: ./Job.Positions.Api
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # HTTP
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Data Source=/app/positions.db"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      FrontEndUrl: "http://localhost:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./Job.Positions.Api/positions.db:/app/positions.db

  ui:
    build:
      context: ./Job.Positions.UI # React app folder
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map the React app to port 3000 locally
    depends_on:
      - api
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:management"
    networks:
      - app-network
    ports:
      - "5672:5672"   # RabbitMQ main communication port
      - "15672:15672" # RabbitMQ management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      
networks:
  app-network:
    driver: bridge