services:
  ui:
    build:
      context: ./Job.Positions.UI
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      
  api:
    build:
      context: ./Job.Positions.Api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:4.0-management"
    ports:
      - "5672:5672"
      - "15672:15672"
